title: TTU Custom Server Resources
description: Documentation and server info for the TTU Minecraft Server.
url: "https://benbowles.me"
theme: minima
baseurl: "/TTU-Custom-Server-Resources"

markdown: kramdown
highlighter: rouge
